### ISSUE TITLE
Failure to parse netMHCpan 4.0 output

### ISSUE THREAD

**Issue by e-dorigatti** [KohlbacherLab/epytope#84]
Parsing predictions from netMHCpan 4.0 fails with the following trace:

```
  File "data_preparation.py", line 204, in get_binding_affinity_process
    res = predictor.predict(batch, alleles)
  File "/tmp/GeneralizedEvDesign/epytope/epytope/EpitopePrediction/External.py", line 191, in predict
    df_result = EpitopePredictionResult.from_dict(result, list(pep_seqs.values()), self.name)
  File "/tmp/GeneralizedEvDesign/epytope/epytope/Core/Result.py", line 160, in from_dict
    df[allele][method][metric][pep] = score
  File "/home/edo/miniconda3/envs/gnv/lib/python3.6/site-packages/pandas/core/series.py", line 1042, in __setitem__
    self._set_with(key, value)
  File "/home/edo/miniconda3/envs/gnv/lib/python3.6/site-packages/pandas/core/series.py", line 1098, in _set_with
    self._set_labels(key, value)
  File "/home/edo/miniconda3/envs/gnv/lib/python3.6/site-packages/pandas/core/series.py", line 1105, in _set_labels
    raise ValueError(f"{key[mask]} not contained in the index")
ValueError: ['L' 'L' 'N' 'G' 'S' 'L' 'A' 'E' 'E'] not contained in the index
```

Reproducing example (I am using the latest version on the `main` branch):

```
from epytope.EpitopePrediction.External import NetMHCpan_4_0
from epytope.Core import Peptide, Allele

predictor = NetMHCpan_4_0()
predictor.predict([Peptide('LLNGSLAEE'), Peptide('KDQQLLGIW')], [Allele('HLA-A*02:01'), Allele('HLA-B*40:01')])
```

The issue seems to be related to pandas indexing (and no response [on StackOverflow](https://stackoverflow.com/questions/55342737/pandas-loc-saying-a-value-is-not-in-index-when-im-pretty-sure-it-is) for a similar problem) and is easy to fix:

```
diff --git a/epytope/Core/Result.py b/epytope/Core/Result.py
index eabb271..8bb5f32 100644
--- a/epytope/Core/Result.py
+++ b/epytope/Core/Result.py
@@ -154,9 +154,10 @@ class EpitopePredictionResult(AResult):
         # Fill DataFrame
         for allele, metrics in d.items():
             for metric, pep_scores in metrics.items():
+                df_slice = df[allele][method][metric]
                 for pep, score in pep_scores.items():
-                    df[allele][method][metric][pep] = score
+                    df_slice[df_slice.index == pep] = score
         return EpitopePredictionResult(df)
```

But maybe some other modules are affected as well?

**Comment by jonasscheid** [comment]
Hi @e-dorigatti!
Before we go into your dependencies, could you try running netmhcpan via the `EpitopepredictionFactory`

Similar like using syfpeithi in the [tutorials](https://github.com/KohlbacherLab/epytope/blob/main/epytope/tutorials/EpitopePrediction.ipynb)
`predictor = EpitopePredictorFactory("Syfpeithi")`
`results = predictor.predict(peptides2, alleles=alleles)
results.head()`
Make sure netmhcpan is in our PATH

Let me know if that worked for you, else we find a solution
Best
Jonas

**Comment by e-dorigatti** [comment]
Hi @jonasscheid, I get the same error with netMHCpan 4 and Syfpeithi created via the `EpitopePredictorFactory`:

```
In [23]: EpitopePredictorFactory("netmhcpan", version='4.0').predict(peps, als)                                                
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)    
~/miniconda3/envs/gnv/lib/python3.6/site-packages/pandas/core/series.py in __setitem__(self, key, value)
   1013         try:
-> 1014             self._set_with_engine(key, value)
   1015         except com.SettingWithCopyError:                                                                               

~/miniconda3/envs/gnv/lib/python3.6/site-packages/pandas/core/series.py in _set_with_engine(self, key, value)
   1053         try:
-> 1054             self.index._engine.set_value(values, key, value)
   1055             return

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.set_value()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.set_value()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

TypeError: 'LLNGSLAEE' is an invalid key

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-23-974f3d0dc2d3> in <module>
----> 1 EpitopePredictorFactory("netmhcpan", version='4.0').predict(peps, als)

~/miniconda3/envs/gnv/lib/python3.6/site-packages/epytope/EpitopePrediction/External.py in predict(self, peptides, alleles, command, options, **kwargs)
    189                              " for given input. Check your epitope length and HLA allele combination.")
    190 
--> 191         df_result = EpitopePredictionResult.from_dict(result, list(pep_seqs.values()), self.name)
    192 
    193         return df_result

~/miniconda3/envs/gnv/lib/python3.6/site-packages/epytope/Core/Result.py in from_dict(d, peps, method)
    156             for metric, pep_scores in metrics.items():
    157                 for pep, score in pep_scores.items():
--> 158                     df[allele][method][metric][pep] = score
    159 
    160         return EpitopePredictionResult(df)

~/miniconda3/envs/gnv/lib/python3.6/site-packages/pandas/core/series.py in __setitem__(self, key, value)
   1040                     pass
   1041 
-> 1042             self._set_with(key, value)
   1043 
   1044         if cacher_needs_updating:

~/miniconda3/envs/gnv/lib/python3.6/site-packages/pandas/core/series.py in _set_with(self, key, value)
   1096                 self._set_values(key.astype(np.bool_), value)
   1097             else:
-> 1098                 self._set_labels(key, value)
   1099 
   1100     def _set_labels(self, key, value):

~/miniconda3/envs/gnv/lib/python3.6/site-packages/pandas/core/series.py in _set_labels(self, key, value)
   1103         mask = indexer == -1
   1104         if mask.any():
-> 1105             raise ValueError(f"{key[mask]} not contained in the index")
   1106         self._set_values(indexer, value)
   1107 

ValueError: ['L' 'L' 'N' 'G' 'S' 'L' 'A' 'E' 'E'] not contained in the index
```



 NetMHCpan 4.1 gives a different error:

```

In [22]: EpitopePredictorFactory("netmhcpan", version='4.1').predict(peps, als)                                                
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-22-e0b62dd96999> in <module>
----> 1 EpitopePredictorFactory("netmhcpan", version='4.1').predict(peps, als)

~/miniconda3/envs/gnv/lib/python3.6/site-packages/epytope/EpitopePrediction/External.py in predict(self, peptides, alleles, command, options, **kwargs)
    171 
    172                     # Obtain parsed output dataframe containing the peptide scores and/or ranks
--> 173                     res_tmp = self.parse_external_result(tmp_out_path)
    174                     for allele_string, scores in res_tmp.items():
    175                         allele = alleles_string[allele_string]

~/miniconda3/envs/gnv/lib/python3.6/site-packages/epytope/EpitopePrediction/External.py in parse_external_result(self, file)
    895             pep_seq = row[PeptideIndex.NETMHCPAN_4_1]
    896             for i, a in enumerate(alleles):
--> 897                 scores[a][pep_seq] = float(row[ScoreIndex.NETMHCPAN_4_1 + i * Offset.NETMHCPAN_4_1])
    898                 ranks[a][pep_seq] = float(row[RankIndex.NETMHCPAN_4_1 + i * Offset.NETMHCPAN_4_1])
    899         # Create dictionary with hierarchy: {'Allele1': {'Score': {'Pep1': Score1, 'Pep2': Score2,..}, 'Rank': {'Pep1': RankScore1, 'Pep2': RankScore2,..}}, 'Allele2':...}

ValueError: could not convert string to float: 'LLNGSLAEE'
```

**Comment by jonasscheid** [comment]
I cannot reproduce your error, I can run it on linux. Can you give me your `conda list` or dependencies you use?

**Comment by e-dorigatti** [comment]
I am also running linux, using a conda environment made from [this package list](https://github.com/SchubertLab/GeneralizedEvDesign/blob/master/environment.yml). FWIF I also tried pandas 0.25.3 instead of 1.0.3 but that did not solve the issue.

**Comment by jonasscheid** [comment]
Ok after downgrading from pandas 1.3.5 to 1.0.3 I could reproduce your error. So the solution would be to upgrade pandas here. Let me know if that worked for you

**Comment by christopher-mohr** [comment]
@e-dorigatti Thanks for reporting this. I would recommend to install it via conda (https://anaconda.org/bioconda/epytope). You can also add it to the `environment.yml`.

**Comment by e-dorigatti** [comment]
Yes that works, thank you. Could you pin a minimum pandas version in your [setup.py](https://github.com/KohlbacherLab/epytope/blob/main/setup.py#L105) before closing?
